backend:
  name: git-gateway
  branch: main

media_folder: "."
public_folder: "/"

collections:
  - name: "clubs"
    label: "Clubs"
    files:
      - name: "clubs"
        label: "Club Listings"
        file: "_data/clubs.json"
        fields:
          - label: "Clubs"
            name: "clubs"
            widget: "list"
            fields:
              - { label: "ID",          name: "id",     widget: "string" }
              - { label: "Name",        name: "name",   widget: "string" }
              - label: "Type"
                name: "type"
                widget: "select"
                options: ["Putter", "Iron", "Wood", "Hybrid", "Driver"]
              - { label: "Ideal Price", name: "ideal",  widget: "number" }
              - { label: "Floor Price", name: "low",    widget: "number" }
              - { label: "OBO",         name: "obo",    widget: "boolean", default: false }
              - { label: "Photos",      name: "photos", widget: "list",    field: { label: "Photo", name: "photo", widget: "string" } }
              - { label: "Description", name: "desc",   widget: "text" }
